{% set name = "coredns" %}
{% set go_pkg_name = "github.com/coredns/" + name %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/coredns/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: fc4902d746eeef5b954a9d3d546cd841766d24a6d4aa7ecf7e2ff832cf818876

build:
  number: 0
  script:
    - go install -v -ldflags "-s -w" .

requirements:
  build:
    - {{ compiler('go') }} 1.13

test:
  commands:
    - coredns -version

about:
  home: https://coredns.io/
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: CoreDNS is a DNS server written in Go that chains plugins
  doc_url: https://coredns.io/manual/toc/
  dev_url: https://github.com/coredns/coredns

extra:
  recipe-maintainers:
    - sodre
