{% set name = "coredns" %}
{% set version = "1.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/coredns/{{ name }}/archive/v{{ version }}.tar.gz  # [not win]
  fn: {{ name }}-{{ version }}.tar.gz  # [not win]
  sha256: 048b1d60c22b2b76335df5fb832995d675d886c51a680f228c5b5c3b778658a2  # [not win]

  url: https://github.com/coredns/{{ name }}/releases/download/v{{ version }}/{{ name }}_{{ version }}_windows_amd64.tgz  # [win]
  fn: {{ name }}-{{ version }}.tgz  # [win]
  sha256: 100bcf2e54e1e1396233d224e4a6c6418086cdb09e72a2f6508b4a5321671ef3  # [win]

build:
  skip: True  # [win32]
  number: 1000

requirements:
  build:
    - make  # [not win]
    - go 1.9.*  # [not win]

test:
  commands:
    - coredns --version

    # Ugly hack because coredns is not a dynamic executable
    - conda inspect linkages -p $PREFIX {{ name|lower }}  # [osx]
    - conda inspect objects -p $PREFIX {{ name|lower }}  # [osx]

about:
  home: https://coredns.io/
  license: Apache-2.0
  license_family: Apache
  summary: CoreDNS is a DNS server written in Go that chains plugins
  doc_url: https://coredns.io/manual/toc/
  dev_url: https://github.com/coredns/coredns

extra:
  recipe-maintainers:
    - sodre
