appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: YE1A+0H9SKSQsn8Wr7FOBcal3anygubpliLXO01lPN83GKJhuMbcS+erQvdjN4SE8lBJXWktxPf5/WSY6UI7I0cMCOoY2i28KHThrH5ynQkgcLasZ+ipXTISMStpnhpMwVwLhCBE0efCidT3MrpRqZo/TY1o8d40gcsNnk/mXVSBtGBMRWJXYxORmAXSFetuGeiHKDez6y1zF90zLCEEwNXTVv/BYdcHANFfUJl8HHGLQ1AMFp3L3BaHja1Xprm/3IkceOpDoRyupwVmuUa20emeuIDigZSHOpljuOk5WWlPoqriSAwlE8xI9xoX79cU+QqPN+ISQll5p5OWHGv9oRQjGuapaIXNlmwLIhCYLRBeVXevLGqjhg1YFhxVQEPt7eGzZ+e75HdbOrU4MKt4gtllngwmYlqbe5NRuiczTFXEsCUi95p6kVsA2ryC/YGh6qBI+CKdrtr0EQsHY4JuAEC/c3tP/ccixHp3m3nAwuZJE1HWASqyn1vv6g3fOfdp4/RRDYeAdJS8BikbXXAEejmkSEiVcJW4no4I+MwaS7lcYNhPY4tzjBuCDSoo0VFMP8Ahw+kjnYeqle7ChGiCTXN2KBlO/TqYfaI4Z9tLHTMbkXRuqe2cn3NS4TuVYthc7UpeJq1eFEHBjKcgoUjEqMiv+gUgvpRUagRi4SuJGVk=}
provider:
  win: azure
bot:
  automerge: true
conda_forge_output_validation: true
